

---
title: "实证分析方法参考文献清单v0.1"
editor: 
  markdown: 
    wrap: 72
---



# 方法类
## 因果推断
- 江艇. 因果推断经验研究中的中介效应与调节效应[J]. 中国工业经济,2022,(05): 100-120. 
  
## 双重差分模型
- 	张征宇,林丽花,曹思力,等. 双重差分设计下固定效应估计量何时可信？——若干有用的建议[J]. 管理世界,2024,40(01): 196-222. 
- 	刘冲,沙学康,张妍. 交错双重差分：处理效应异质性与估计方法选择[J]. 数量经济技术经济研究,2022,39(09): 177-204. 
- 	黄炜,张子尧,刘安然. 从双重差分法到事件研究法[J]. 产业经济评论,2022,(02): 17-36. 
- 	徐佳,崔静波. 低碳城市和企业绿色技术创新[J]. 中国工业经济,2020,(12): 178-196. 
- 	刘瑞明,赵仁杰. 国家高新区推动了地区经济发展吗?——基于双重差分方法的验证[J]. 管理世界,2015,(08): 30-38. 

## 断点回归模型
- 	Chen Y, Ebenstein A, Greenstone M, et al. Evidence on the impact of - sustained exposure to air pollution on life expectancy from China’s Huai - River policy[J]. Proceedings of  National Academy of Sciences, 2013, 110- (32): 12936-12941.
- 	Ebenstein A, Fan M, Greenstone M, et al. New evidence on the impact of - sustained exposure to air pollution on life expectancy from China’s Huai - River Policy[J]. Proceedings the National Academy of Sciences, 2017, 114- (39): 10384-10389.
- 	李明,李德刚,冯强.中国减税的经济效应评估——基于所得税分享改革“准自然试验”[J]. 经济研究,2018,53(07): 121-135.
- 	陈林,万攀兵,许莹盈.混合所有制企业的股权结构与创新行为——基于自然实验与断点回归的实证检验[J]. 管理世界,2019,35(10): 186-205.

## 政策评估模型
- 陶旭辉,郭峰. 异质性政策效应评估与机器学习方法：研究进展与未来方向[J]. 管理世界, 2023, 39 (11): 216-237.

## 空间计量模型
-	Dian, J., Song, T., & Li, S. (2024). Facilitating or inhibiting? Spatial effects of the digital economy affecting urban green technology innovation. Energy Economics, 129, 107223.
-	白俊红,王钺,蒋伏心,等. 研发要素流动、空间知识溢出与经济增长[J]. 经济研究, 2017, 52 (07): 109-123.

## 人工智能方法应用
-	陶旭辉,郭峰. 异质性政策效应评估与机器学习方法：研究进展与未来方向[J]. 管理世界, 2023, 39 (11): 216-237.
-	张涛,李均超. 网络基础设施、包容性绿色增长与地区差距——基于双重机器学习的因果推断[J]. 数量经济技术经济研究, 2023, 40 (04): 113-135.

## 工具变量
- 	Adao, R., Kolesár, M., & Morales, E. (2019). Shift-share designs: Theory and inference. The Quarterly Journal of Economics, 134(4), 1949-2010.
- 	Borusyak, K., Hull, P., & Jaravel, X. (2022). Quasi-experimental shift-share research designs. The Review of Economic Studies, 89(1), 181-213.
- 	Goldsmith-Pinkham, P., Sorkin, I., & Swift, H. (2020). Bartik instruments: when, why, and how. American Economic Review, 110(8), 2586-2624.
- 	Borusyak, K., & Hull, P. (2023). Nonrandom exposure to exogenous shocks. Econometrica, 91(6), 2155-2185.
- 	Bellemare, M. F., T. Masaki, T. B. Pepinsky. (2017). Lagged explanatory vaiables and the estimation of causal effect, The Journal of Politics, 79 (3)- 49-963. 
- 	余振,李萌,庄额嘉.  Bartik工具变量法在因果识别中的应用与检验[J]. 数量经济技术经济- 究,2024,1-21.
- 	Borusyak, K., Hull, P., & Jaravel, X. (2024). A practical guide to shift-share instruments (No. w33236). National Bureau of Economic Research.

## 控制变量
- 张子尧,黄炜. 实证研究中的控制变量选择：原理与原则 [J]. 管理世界, 2025, 41 (10): 210-234.
- Cinelli, C., Forney, A., & Pearl, J. (2024). A crash course in good and bad controls. Sociological Methods & Research, 53(3), 1071-1104.
